services:
  web:
    image: ghcr.io/mealie-recipes/mealie:v3.6.1
    hostname: mealie_web_1
    container_name: mealie_web_1
    restart: unless-stopped
    ports:
      - "9925:9000"
    environment:
      ALLOW_SIGNUP: "true"
      PUID: 1000
      PGID: 1000
      MAX_WORKERS: 1
      WEB_CONCURRENCY: 1
      TZ: "${TZ:-Australia/Brisbane}"
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
