services:
  insight:
    image: redis/redisinsight
    hostname: redis_insight_1
    container_name: redis_insight_1
    init: true
    user: "1000:1000"
    restart: unless-stopped
    ports:
      - "5540:5540"
    environment:
      RI_REDIS_HOST: redis_server_1
      RI_REDIS_PORT: 6379
    volumes:
      - "${APP_DATA_DIR}/data/insight-data:/data:rw"
    depends_on:
      - server

  server:
    image: redis:8.4.0-alpine
    hostname: redis_server_1
    container_name: redis_server_1
    init: true
    user: "1000:1000"
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - "${APP_DATA_DIR}/data/redis-data:/data:rw"
