services:
  app_proxy:
    environment:
      APP_HOST: postgres_pgadmin_1
      APP_PORT: 80

  pgadmin:
    image: dpage/pgadmin4:latest
    hostname: postgres_pgadmin_1
    container_name: postgres_pgadmin_1
    init: true
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: "umbrel@localhost.com"
      PGADMIN_DEFAULT_PASSWORD: "umbrel"
    volumes:
      - "${APP_DATA_DIR}/data/pgadmin-data:/var/lib/pgadmin:rw"
      - "${APP_DATA_DIR}/initial/servers.json:/pgadmin4/servers.json:ro"
    depends_on:
      - server

  server:
    image: postgres:17.7-alpine
    hostname: postgres_server_1
    container_name: postgres_server_1
    init: true
    restart: unless-stopped
    environment:
      PGID: "1000"
      PUID: "1000"
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      TZ: "Australia/Brisbane"
    ports:
      - "5432:5432"
    volumes:
      - "${APP_DATA_DIR}/data/pgdata:/var/lib/postgresql/data:rw"
