services:
  server:
    image: jc21/nginx-proxy-manager:latest
    hostname: nginx_proxy_manager_server_1
    container_name: nginx_proxy_manager_server_1
    init: true
    restart: unless-stopped
    ports:
      - "81:81"
      - "443:443"
    volumes:
      - "${APP_DATA_DIR}/data/npm-data:/data:rw"
      - "${APP_DATA_DIR}/data/letsencrypt:/etc/letsencrypt:rw"
