services:
  app_proxy:
    environment:
      APP_HOST: jc21-hashicorp-vault_server_1
      APP_PORT: 8200

  server:
    image: getumbrel/community-app-store-hello-world:latest
    user: "1000:1000"
    init: true
