services:
  app_proxy:
    environment:
      APP_HOST: jc21-hashicorp-vault_server_1
      APP_PORT: 8200

  server:
    image: hashicorp/vault:latest
    init: true
    restart: unless-stopped
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
      VAULT_API_ADDR: "http://0.0.0.0:8200"
      VAULT_LOCAL_CONFIG: |
        {
          "backend": {
            "file": {
              "path": "/vault/file"
            }
          },
          "listener": {
            "tcp": {
              "address": "0.0.0.0:8200",
              "tls_disable": true
            }
          },
          "ui": true
        }
    cap_add:
      - IPC_LOCK
    volumes:
      - "${APP_DATA_DIR}/data/vault-data:/vault/file:rw"
      - "${APP_DATA_DIR}/data/vault-logs:/vault/logs:rw"
    command: server
